//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteGloomApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteGloomApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string buscarPartidaBtnUnirse {
            get {
                return ResourceManager.GetString("buscarPartidaBtnUnirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar partida.
        /// </summary>
        public static string buscarPartidaInstruccion {
            get {
                return ResourceManager.GetString("buscarPartidaInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida.
        /// </summary>
        public static string buscarPartidaPartida {
            get {
                return ResourceManager.GetString("buscarPartidaPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pierde un turno.
        /// </summary>
        public static string cartaPerderTurno {
            get {
                return ResourceManager.GetString("cartaPerderTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecicona un jugador para quitarle una carta.
        /// </summary>
        public static string cartaQuitarCarta {
            get {
                return ResourceManager.GetString("cartaQuitarCarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roba una carta.
        /// </summary>
        public static string cartaRobarCarta1 {
            get {
                return ResourceManager.GetString("cartaRobarCarta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roba dos cartas.
        /// </summary>
        public static string cartaRobarCarta2 {
            get {
                return ResourceManager.GetString("cartaRobarCarta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta que la muerte nos separe.
        /// </summary>
        public static string cartaSaltarJugador {
            get {
                return ResourceManager.GetString("cartaSaltarJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala.
        /// </summary>
        public static string crearPartidaBtnCrearSala {
            get {
                return ResourceManager.GetString("crearPartidaBtnCrearSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string crearPartidaInstruccion {
            get {
                return ResourceManager.GetString("crearPartidaInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la sala.
        /// </summary>
        public static string crearPartidaNombreSala {
            get {
                return ResourceManager.GetString("crearPartidaNombreSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de jugadores.
        /// </summary>
        public static string crearPartidaNumeroJugadores {
            get {
                return ResourceManager.GetString("crearPartidaNumeroJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de partida.
        /// </summary>
        public static string crearPartidaTipoPartida {
            get {
                return ResourceManager.GetString("crearPartidaTipoPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de sala.
        /// </summary>
        public static string crearPartidaTipoSala {
            get {
                return ResourceManager.GetString("crearPartidaTipoSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba el código de sala.
        /// </summary>
        public static string entradaPrivadaPartidaInstruccion {
            get {
                return ResourceManager.GetString("entradaPrivadaPartidaInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribir mensaje.
        /// </summary>
        public static string escribirMensajeInstrucción {
            get {
                return ResourceManager.GetString("escribirMensajeInstrucción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La voz del destino ha hablado y yo he respondido, he ganado.
        /// </summary>
        public static string finMiniComentarioGanador {
            get {
                return ResourceManager.GetString("finMiniComentarioGanador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La voz del destino ha hablado y yo he respondido, he ganado.
        /// </summary>
        public static string finMiniInstruccionGanador {
            get {
                return ResourceManager.GetString("finMiniInstruccionGanador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de puntos de autoestima.
        /// </summary>
        public static string finMiniIntruccionPuntos {
            get {
                return ResourceManager.GetString("finMiniIntruccionPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Felicitaciones al jugador que con astucia y crueldad ha llevado a todos los demás al borde de la desesperación ¡La victoria es tuya!.
        /// </summary>
        public static string finPartidaFelicitacionLeyenda {
            get {
                return ResourceManager.GetString("finPartidaFelicitacionLeyenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La voz del destino ha hablado y yo he respondido, he ganado.
        /// </summary>
        public static string finPartidaMiniLeyenda {
            get {
                return ResourceManager.GetString("finPartidaMiniLeyenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string globalApellidos {
            get {
                return ResourceManager.GetString("globalApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string globalChat {
            get {
                return ResourceManager.GetString("globalChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string globalContraseña {
            get {
                return ResourceManager.GetString("globalContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string globalCorreo {
            get {
                return ResourceManager.GetString("globalCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar.
        /// </summary>
        public static string globalEmpezar {
            get {
                return ResourceManager.GetString("globalEmpezar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string globalEnviar {
            get {
                return ResourceManager.GetString("globalEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string globalInvitar {
            get {
                return ResourceManager.GetString("globalInvitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar jugadores.
        /// </summary>
        public static string globalInvitarJugadores {
            get {
                return ResourceManager.GetString("globalInvitarJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string globalJugadores {
            get {
                return ResourceManager.GetString("globalJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string globalListo {
            get {
                return ResourceManager.GetString("globalListo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string globalNombre {
            get {
                return ResourceManager.GetString("globalNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre usuario.
        /// </summary>
        public static string globalNombreUsuario {
            get {
                return ResourceManager.GetString("globalNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privada.
        /// </summary>
        public static string globalPartidaPrivada {
            get {
                return ResourceManager.GetString("globalPartidaPrivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pública.
        /// </summary>
        public static string globalPartidaPublica {
            get {
                return ResourceManager.GetString("globalPartidaPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abelith.
        /// </summary>
        public static string historiaAbelith {
            get {
                return ResourceManager.GetString("historiaAbelith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Angelus.
        /// </summary>
        public static string historiaAngelus {
            get {
                return ResourceManager.GetString("historiaAngelus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arialyn.
        /// </summary>
        public static string historiaArialyn {
            get {
                return ResourceManager.GetString("historiaArialyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aris.
        /// </summary>
        public static string historiaAris {
            get {
                return ResourceManager.GetString("historiaAris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Didorian.
        /// </summary>
        public static string historiaDidorian {
            get {
                return ResourceManager.GetString("historiaDidorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gaia.
        /// </summary>
        public static string historiaGaia {
            get {
                return ResourceManager.GetString("historiaGaia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganó.
        /// </summary>
        public static string historialGanador {
            get {
                return ResourceManager.GetString("historialGanador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida a sido.
        /// </summary>
        public static string historialHa {
            get {
                return ResourceManager.GetString("historialHa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de partidas.
        /// </summary>
        public static string historialInstruccion {
            get {
                return ResourceManager.GetString("historialInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugó con.
        /// </summary>
        public static string historialJugoCon {
            get {
                return ResourceManager.GetString("historialJugoCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorenzeo.
        /// </summary>
        public static string historiaLorenzeo {
            get {
                return ResourceManager.GetString("historiaLorenzeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perdió.
        /// </summary>
        public static string historialPerdedor {
            get {
                return ResourceManager.GetString("historialPerdedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string historialTipo {
            get {
                return ResourceManager.GetString("historialTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Luan.
        /// </summary>
        public static string historiaLuan {
            get {
                return ResourceManager.GetString("historiaLuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lusiel.
        /// </summary>
        public static string historiaLusiel {
            get {
                return ResourceManager.GetString("historiaLusiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganador.
        /// </summary>
        public static string historialVictoria {
            get {
                return ResourceManager.GetString("historialVictoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Merit.
        /// </summary>
        public static string historiaMerit {
            get {
                return ResourceManager.GetString("historiaMerit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neferu.
        /// </summary>
        public static string historiaNeferu {
            get {
                return ResourceManager.GetString("historiaNeferu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pablian.
        /// </summary>
        public static string historiaPablian {
            get {
                return ResourceManager.GetString("historiaPablian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del personaje.
        /// </summary>
        public static string historiaPersonajeInstruccion {
            get {
                return ResourceManager.GetString("historiaPersonajeInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seti.
        /// </summary>
        public static string historiaSeti {
            get {
                return ResourceManager.GetString("historiaSeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobek.
        /// </summary>
        public static string historiaSobek {
            get {
                return ResourceManager.GetString("historiaSobek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tucani.
        /// </summary>
        public static string historiaTucani {
            get {
                return ResourceManager.GetString("historiaTucani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zael.
        /// </summary>
        public static string historiaZael {
            get {
                return ResourceManager.GetString("historiaZael", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar partida.
        /// </summary>
        public static string inicioBtnBuscarPartida {
            get {
                return ResourceManager.GetString("inicioBtnBuscarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string inicioBtnCerrarSesion {
            get {
                return ResourceManager.GetString("inicioBtnCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string inicioBtnCrearPartida {
            get {
                return ResourceManager.GetString("inicioBtnCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial partidas.
        /// </summary>
        public static string inicioBtnHistorialDePartidas {
            get {
                return ResourceManager.GetString("inicioBtnHistorialDePartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string inicioBtnListaDeAmigos {
            get {
                return ResourceManager.GetString("inicioBtnListaDeAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mini historia.
        /// </summary>
        public static string inicioBtnMiniHistoria {
            get {
                return ResourceManager.GetString("inicioBtnMiniHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver personajes.
        /// </summary>
        public static string inicioBtnVerPersonajes {
            get {
                return ResourceManager.GetString("inicioBtnVerPersonajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para acceder a todas las funcionalidades tiene que registrarse.
        /// </summary>
        public static string inicioInstruccionInvitado {
            get {
                return ResourceManager.GetString("inicioInstruccionInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string inicioSesionBtnIniciarSesion {
            get {
                return ResourceManager.GetString("inicioSesionBtnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string inicioSesionBtnJugarComoInvitado {
            get {
                return ResourceManager.GetString("inicioSesionBtnJugarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string inicioSesionBtnRegistrarse {
            get {
                return ResourceManager.GetString("inicioSesionBtnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar foto.
        /// </summary>
        public static string instruccionSeleccionarFoto {
            get {
                return ResourceManager.GetString("instruccionSeleccionarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar una invitación por correo.
        /// </summary>
        public static string invitarAmistadesEnviarCorreo {
            get {
                return ResourceManager.GetString("invitarAmistadesEnviarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis amigos.
        /// </summary>
        public static string listaAmigosBtnMisAmigos {
            get {
                return ResourceManager.GetString("listaAmigosBtnMisAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver solicitudes de amistad.
        /// </summary>
        public static string listaAmigosbtnVerSolicitud {
            get {
                return ResourceManager.GetString("listaAmigosbtnVerSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar jugador.
        /// </summary>
        public static string listaAmigosInstruccion {
            get {
                return ResourceManager.GetString("listaAmigosInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizado exitosamente.
        /// </summary>
        public static string mensajeActualizacionExitosa {
            get {
                return ResourceManager.GetString("mensajeActualizacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El chat no se encuentra habilitado.
        /// </summary>
        public static string mensajeChatNoHabilitado {
            get {
                return ResourceManager.GetString("mensajeChatNoHabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación por correo enviada exitosamente.
        /// </summary>
        public static string mensajeCorreoEnviadoExitoso {
            get {
                return ResourceManager.GetString("mensajeCorreoEnviadoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La invitación por correo no pudo ser enviada, inténtelo de nuevo más tarde.
        /// </summary>
        public static string mensajeCorreoEnviadoFallido {
            get {
                return ResourceManager.GetString("mensajeCorreoEnviadoFallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario registrado.
        /// </summary>
        public static string mensajeExp01 {
            get {
                return ResourceManager.GetString("mensajeExp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo registrado.
        /// </summary>
        public static string mensajeExp02 {
            get {
                return ResourceManager.GetString("mensajeExp02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado.
        /// </summary>
        public static string mensajeExp03 {
            get {
                return ResourceManager.GetString("mensajeExp03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este usuario ya es amigo suyo.
        /// </summary>
        public static string mensajeExp04 {
            get {
                return ResourceManager.GetString("mensajeExp04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se ha enviado una solicitud a este jugador, espere a su respuesta.
        /// </summary>
        public static string mensajeExp05 {
            get {
                return ResourceManager.GetString("mensajeExp05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para agregar un amigo, debes seleccionar el perfil de otra persona, asegúrate de enviar la solicitud a alguien más..
        /// </summary>
        public static string mensajeExp06 {
            get {
                return ResourceManager.GetString("mensajeExp06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha seleccionado a un jugador para enviar solicitud.
        /// </summary>
        public static string mensajeExp07 {
            get {
                return ResourceManager.GetString("mensajeExp07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este nombre para la sala ya está siendo ocupado, intente ingresando otro nombre diferente..
        /// </summary>
        public static string mensajeExp08 {
            get {
                return ResourceManager.GetString("mensajeExp08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este código ya existe..
        /// </summary>
        public static string mensajeExp09 {
            get {
                return ResourceManager.GetString("mensajeExp09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ninguna sala con ese código o identificador, verifique que estén correctas..
        /// </summary>
        public static string mensajeExp10 {
            get {
                return ResourceManager.GetString("mensajeExp10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excepción 10054.
        /// </summary>
        public static string mensajeExp10054 {
            get {
                return ResourceManager.GetString("mensajeExp10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excpecón 100060.
        /// </summary>
        public static string mensajeExp10060 {
            get {
                return ResourceManager.GetString("mensajeExp10060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ingresado no es válido. Debe tener entre 3 y 255 caracteres, sin más de dos espacios seguidos y seguir el formato usuario@dominio.com..
        /// </summary>
        public static string mensajeExp11 {
            get {
                return ResourceManager.GetString("mensajeExp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excepción 11001.
        /// </summary>
        public static string mensajeExp11001 {
            get {
                return ResourceManager.GetString("mensajeExp11001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aún no ha seleccionado una imagen para su perfil.
        /// </summary>
        public static string mensajeExp12 {
            get {
                return ResourceManager.GetString("mensajeExp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario incorrecto.
        /// </summary>
        public static string mensajeExp13 {
            get {
                return ResourceManager.GetString("mensajeExp13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este personaje ya está seleccionado.
        /// </summary>
        public static string mensajeExp14 {
            get {
                return ResourceManager.GetString("mensajeExp14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No todos los jugadores han seleccionado un personaje.
        /// </summary>
        public static string mensajeExp15 {
            get {
                return ResourceManager.GetString("mensajeExp15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo conectar el servidor con todos los jugadores.
        /// </summary>
        public static string mensajeExp16 {
            get {
                return ResourceManager.GetString("mensajeExp16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala aun no está llena espere a los demás jugadores.
        /// </summary>
        public static string mensajeExp17 {
            get {
                return ResourceManager.GetString("mensajeExp17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se termino el tiempo de espera del servidor, intente realizar la operación más tarde.
        /// </summary>
        public static string mensajeExp18 {
            get {
                return ResourceManager.GetString("mensajeExp18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excepción 18456.
        /// </summary>
        public static string mensajeExp18456 {
            get {
                return ResourceManager.GetString("mensajeExp18456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede dar clic al botón &quot;Listo&quot; si no ha seleccionado un personaje.
        /// </summary>
        public static string mensajeExp19 {
            get {
                return ResourceManager.GetString("mensajeExp19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede agarrar más de 7 cartas.
        /// </summary>
        public static string mensajeExp20 {
            get {
                return ResourceManager.GetString("mensajeExp20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No quedan más cartas en el mazo..
        /// </summary>
        public static string mensajeExp21 {
            get {
                return ResourceManager.GetString("mensajeExp21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un problema con el servidor. Intente nuevamente más tarde..
        /// </summary>
        public static string mensajeExp22 {
            get {
                return ResourceManager.GetString("mensajeExp22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala no es pública o no existe..
        /// </summary>
        public static string mensajeExp23 {
            get {
                return ResourceManager.GetString("mensajeExp23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique el código de la sala..
        /// </summary>
        public static string mensajeExp24 {
            get {
                return ResourceManager.GetString("mensajeExp24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra archivo para enviar correo..
        /// </summary>
        public static string mensajeExp25 {
            get {
                return ResourceManager.GetString("mensajeExp25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se tiene acceso al archivo para enviar correo..
        /// </summary>
        public static string mensajeExp26 {
            get {
                return ResourceManager.GetString("mensajeExp26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato inválido de correo..
        /// </summary>
        public static string mensajeExp27 {
            get {
                return ResourceManager.GetString("mensajeExp27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el correo..
        /// </summary>
        public static string mensajeExp28 {
            get {
                return ResourceManager.GetString("mensajeExp28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problema al enviar correo..
        /// </summary>
        public static string mensajeExp29 {
            get {
                return ResourceManager.GetString("mensajeExp29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación de envió de correo no válida..
        /// </summary>
        public static string mensajeExp30 {
            get {
                return ResourceManager.GetString("mensajeExp30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha seleccionado una familia.
        /// </summary>
        public static string mensajeExp31 {
            get {
                return ResourceManager.GetString("mensajeExp31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No todos los jugadores han seleccionado una familia.
        /// </summary>
        public static string mensajeExp32 {
            get {
                return ResourceManager.GetString("mensajeExp32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede dar clic al botón &quot;Listo&quot; si no ha seleccionado una familia.
        /// </summary>
        public static string mensajeExp33 {
            get {
                return ResourceManager.GetString("mensajeExp33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala ya está llena, no puede ingresar.
        /// </summary>
        public static string mensajeExp34 {
            get {
                return ResourceManager.GetString("mensajeExp34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Incorrecto.
        /// </summary>
        public static string mensajeExp35 {
            get {
                return ResourceManager.GetString("mensajeExp35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario incorrecto.
        /// </summary>
        public static string mensajeExp36 {
            get {
                return ResourceManager.GetString("mensajeExp36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cumple con el formato la contraseña.
        /// </summary>
        public static string mensajeExp37 {
            get {
                return ResourceManager.GetString("mensajeExp37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador ya no tiene cartas para quitar.
        /// </summary>
        public static string mensajeExp38 {
            get {
                return ResourceManager.GetString("mensajeExp38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida está en progreso. ¡Únete a la siguiente!.
        /// </summary>
        public static string mensajeExp39 {
            get {
                return ResourceManager.GetString("mensajeExp39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un jugador para aplicar el castigo.
        /// </summary>
        public static string mensajeExp40 {
            get {
                return ResourceManager.GetString("mensajeExp40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con la base de datos.
        /// </summary>
        public static string mensajeExp41 {
            get {
                return ResourceManager.GetString("mensajeExp41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el correo del amigo.
        /// </summary>
        public static string mensajeExp42 {
            get {
                return ResourceManager.GetString("mensajeExp42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida ya se acabó.
        /// </summary>
        public static string mensajeExp43 {
            get {
                return ResourceManager.GetString("mensajeExp43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si deseas matar a alguien o a tu personaje, necesita tener mínimo -400 de vida.
        /// </summary>
        public static string mensajeExp44 {
            get {
                return ResourceManager.GetString("mensajeExp44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede automatar así mismo.
        /// </summary>
        public static string mensajeExp45 {
            get {
                return ResourceManager.GetString("mensajeExp45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya ha iniciado sesión anteriormente, cerre la sesión de ese dispositivo si desea continuar aquí.
        /// </summary>
        public static string mensajeExp46 {
            get {
                return ResourceManager.GetString("mensajeExp46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de jugadores conectados no coincide con el número de jugadores esperados..
        /// </summary>
        public static string mensajeExp47 {
            get {
                return ResourceManager.GetString("mensajeExp47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan jugadores por seleccionar una familia..
        /// </summary>
        public static string mensajeExp48 {
            get {
                return ResourceManager.GetString("mensajeExp48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay familias seleccionadas para esta sala..
        /// </summary>
        public static string mensajeExp49 {
            get {
                return ResourceManager.GetString("mensajeExp49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay información de la sala..
        /// </summary>
        public static string mensajeExp50 {
            get {
                return ResourceManager.GetString("mensajeExp50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo no tiene personajes asociados.
        /// </summary>
        public static string mensajeExp51 {
            get {
                return ResourceManager.GetString("mensajeExp51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El familiar objetivo no existe.
        /// </summary>
        public static string mensajeExp52 {
            get {
                return ResourceManager.GetString("mensajeExp52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excpeción 53.
        /// </summary>
        public static string mensajeExp53 {
            get {
                return ResourceManager.GetString("mensajeExp53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El familiar objetivo no pertenece a la familia del jugador..
        /// </summary>
        public static string mensajeExp54 {
            get {
                return ResourceManager.GetString("mensajeExp54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excepción 54060.
        /// </summary>
        public static string mensajeExp54060 {
            get {
                return ResourceManager.GetString("mensajeExp54060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala no encontrada..
        /// </summary>
        public static string mensajeExp55 {
            get {
                return ResourceManager.GetString("mensajeExp55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe ser entre 4 y 255 caracteres, sin espacios ni caracteres especiales..
        /// </summary>
        public static string mensajeExp56 {
            get {
                return ResourceManager.GetString("mensajeExp56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador no está registrado.
        /// </summary>
        public static string mensajeExp57 {
            get {
                return ResourceManager.GetString("mensajeExp57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique su conexión al internet o espera que se reestablezca la señal.
        /// </summary>
        public static string mensajeExp58 {
            get {
                return ResourceManager.GetString("mensajeExp58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un problema con el servidor, lo sentimos, tiene que volver a iniciar su sesión y esperar a que se reestablezca..
        /// </summary>
        public static string mensajeExp59 {
            get {
                return ResourceManager.GetString("mensajeExp59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un problema con el servidor, por favor, espere a que se reestablezca la señal.
        /// </summary>
        public static string mensajeExp60 {
            get {
                return ResourceManager.GetString("mensajeExp60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron salas activas..
        /// </summary>
        public static string mensajeExp61 {
            get {
                return ResourceManager.GetString("mensajeExp61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona una sala..
        /// </summary>
        public static string mensajeExp62 {
            get {
                return ResourceManager.GetString("mensajeExp62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te has unido a la sala pública correctamente..
        /// </summary>
        public static string mensajeExp63 {
            get {
                return ResourceManager.GetString("mensajeExp63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de acceso no proporcionado..
        /// </summary>
        public static string mensajeExp64 {
            get {
                return ResourceManager.GetString("mensajeExp64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te has unido a la sala privada correctamente..
        /// </summary>
        public static string mensajeExp65 {
            get {
                return ResourceManager.GetString("mensajeExp65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te has unido a la sala correctamente..
        /// </summary>
        public static string mensajeExp66 {
            get {
                return ResourceManager.GetString("mensajeExp66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo unir a la sala. Verifica el código de acceso..
        /// </summary>
        public static string mensajeExp67 {
            get {
                return ResourceManager.GetString("mensajeExp67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes enviar un mensaje vacío..
        /// </summary>
        public static string mensajeExp68 {
            get {
                return ResourceManager.GetString("mensajeExp68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha tardado mucho para elegir para quien utilizará la carta.
        /// </summary>
        public static string mensajeExp69 {
            get {
                return ResourceManager.GetString("mensajeExp69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar una carta antes de usarla..
        /// </summary>
        public static string mensajeExp70 {
            get {
                return ResourceManager.GetString("mensajeExp70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un usuario y personaje objetivo antes de continuar..
        /// </summary>
        public static string mensajeExp71 {
            get {
                return ResourceManager.GetString("mensajeExp71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un personaje objetivo antes de continuar..
        /// </summary>
        public static string mensajeExp72 {
            get {
                return ResourceManager.GetString("mensajeExp72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar un usuario y un personaje objetivo para continuar..
        /// </summary>
        public static string mensajeExp73 {
            get {
                return ResourceManager.GetString("mensajeExp73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay jugadores conectados en la sala..
        /// </summary>
        public static string mensajeExp74 {
            get {
                return ResourceManager.GetString("mensajeExp74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron personajes para el usuario seleccionado..
        /// </summary>
        public static string mensajeExp75 {
            get {
                return ResourceManager.GetString("mensajeExp75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar un personaje objetivo para continuar..
        /// </summary>
        public static string mensajeExp76 {
            get {
                return ResourceManager.GetString("mensajeExp76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha iniciado la expulsión del jugador: .
        /// </summary>
        public static string mensajeExpuslion {
            get {
                return ResourceManager.GetString("mensajeExpuslion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has salido de la sala y esta ha sido eliminada..
        /// </summary>
        public static string mensajeHaSalidoDeSala {
            get {
                return ResourceManager.GetString("mensajeHaSalidoDeSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha sido expulsado de la sala.
        /// </summary>
        public static string mensajeHaSidoExpulsado {
            get {
                return ResourceManager.GetString("mensajeHaSidoExpulsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha tardado mucho para elegir para quien utilizará la carta.
        /// </summary>
        public static string mensajeMiniPartidaTiempoAgotado {
            get {
                return ResourceManager.GetString("mensajeMiniPartidaTiempoAgotado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay jugadores disponibles para expulsar..
        /// </summary>
        public static string mensajeNoJugadoresParaExpulsar {
            get {
                return ResourceManager.GetString("mensajeNoJugadoresParaExpulsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Partida creada con éxito!.
        /// </summary>
        public static string mensajePartidaCreadaExitosa {
            get {
                return ResourceManager.GetString("mensajePartidaCreadaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje de Exito para el Registro.
        /// </summary>
        public static string mensajeRegistroJugadorExito {
            get {
                return ResourceManager.GetString("mensajeRegistroJugadorExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje de falla para el registro.
        /// </summary>
        public static string mensajeRegistroJugadorFallido {
            get {
                return ResourceManager.GetString("mensajeRegistroJugadorFallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala ya no está activa. Regresando al menú principal..
        /// </summary>
        public static string mensajeSalaPartida {
            get {
                return ResourceManager.GetString("mensajeSalaPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un jugador para continuar..
        /// </summary>
        public static string mensajeSeleccionJugador {
            get {
                return ResourceManager.GetString("mensajeSeleccionJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu solicitud de amistad se ha enviado exitosamente.
        /// </summary>
        public static string mensajeSolcitudEnviadaExito {
            get {
                return ResourceManager.GetString("mensajeSolcitudEnviadaExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible crear una sala Mini historia pública, sólo puede ser privada..
        /// </summary>
        public static string mensajeTipoPartidaNoPermitida {
            get {
                return ResourceManager.GetString("mensajeTipoPartidaNoPermitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        public static string mensajeTituloAdvertencia {
            get {
                return ResourceManager.GetString("mensajeTituloAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exito.
        /// </summary>
        public static string mensajeTituloExito {
            get {
                return ResourceManager.GetString("mensajeTituloExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion.
        /// </summary>
        public static string mensajeTituloInformacion {
            get {
                return ResourceManager.GetString("mensajeTituloInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar.
        /// </summary>
        public static string miniBtnEmpezar {
            get {
                return ResourceManager.GetString("miniBtnEmpezar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        public static string miniHisotriaInstruccionCodigo {
            get {
                return ResourceManager.GetString("miniHisotriaInstruccionCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala mini-historia.
        /// </summary>
        public static string miniHistoriaEncabezado {
            get {
                return ResourceManager.GetString("miniHistoriaEncabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar familiar.
        /// </summary>
        public static string miniHistoriaInstruccionFamiliar {
            get {
                return ResourceManager.GetString("miniHistoriaInstruccionFamiliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de sala.
        /// </summary>
        public static string miniHistoriaNumeroSala {
            get {
                return ResourceManager.GetString("miniHistoriaNumeroSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar jugadores.
        /// </summary>
        public static string miniInvitarJugadores {
            get {
                return ResourceManager.GetString("miniInvitarJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string miniJugadores {
            get {
                return ResourceManager.GetString("miniJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia.
        /// </summary>
        public static string palabraFamilia {
            get {
                return ResourceManager.GetString("palabraFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganador.
        /// </summary>
        public static string palabraGanador {
            get {
                return ResourceManager.GetString("palabraGanador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string palabraJugador {
            get {
                return ResourceManager.GetString("palabraJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vida total.
        /// </summary>
        public static string palabraVidaTotal {
            get {
                return ResourceManager.GetString("palabraVidaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descartar.
        /// </summary>
        public static string partidaBtnDescartar {
            get {
                return ResourceManager.GetString("partidaBtnDescartar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string partidaBtnExpulsar {
            get {
                return ResourceManager.GetString("partidaBtnExpulsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mini historia.
        /// </summary>
        public static string partidaBtnMiniHistoria {
            get {
                return ResourceManager.GetString("partidaBtnMiniHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string partidaBtnNormal {
            get {
                return ResourceManager.GetString("partidaBtnNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privada.
        /// </summary>
        public static string partidaBtnPrivada {
            get {
                return ResourceManager.GetString("partidaBtnPrivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pública.
        /// </summary>
        public static string partidaBtnPublica {
            get {
                return ResourceManager.GetString("partidaBtnPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usar.
        /// </summary>
        public static string partidaBtnUsar {
            get {
                return ResourceManager.GetString("partidaBtnUsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de la partida.
        /// </summary>
        public static string partidaFinPartida {
            get {
                return ResourceManager.GetString("partidaFinPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida terminó sin ganador.
        /// </summary>
        public static string partidaFinSinGanador {
            get {
                return ResourceManager.GetString("partidaFinSinGanador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione personaje objetivo.
        /// </summary>
        public static string partidaInstruccionSeleccionarPersonajeObjetivo {
            get {
                return ResourceManager.GetString("partidaInstruccionSeleccionarPersonajeObjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione usuario objetivo.
        /// </summary>
        public static string partidaInstruccionSeleccionarUsuario {
            get {
                return ResourceManager.GetString("partidaInstruccionSeleccionarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un personaje de tu familia:.
        /// </summary>
        public static string partidaIntruccionSeleciconaPersonajeFamilia {
            get {
                return ResourceManager.GetString("partidaIntruccionSeleciconaPersonajeFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un personaje de tu familia para aplicar la carta de muerte:.
        /// </summary>
        public static string partidaIntruccionSeleciconaPersonajeFamiliaMuerte {
            get {
                return ResourceManager.GetString("partidaIntruccionSeleciconaPersonajeFamiliaMuerte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string perfilBtnCambiarDatos {
            get {
                return ResourceManager.GetString("perfilBtnCambiarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto.
        /// </summary>
        public static string perfilFoto {
            get {
                return ResourceManager.GetString("perfilFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string registrarseBtnRegistrar {
            get {
                return ResourceManager.GetString("registrarseBtnRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona ícono de perfil.
        /// </summary>
        public static string registroInstruccionIcono {
            get {
                return ResourceManager.GetString("registroInstruccionIcono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los jugadores que coinciden con la búsqueda son.
        /// </summary>
        public static string resultadoAmistad {
            get {
                return ResourceManager.GetString("resultadoAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string salaBtnListo {
            get {
                return ResourceManager.GetString("salaBtnListo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Corbat.
        /// </summary>
        public static string salaDescripcionCorbat {
            get {
                return ResourceManager.GetString("salaDescripcionCorbat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Garlo.
        /// </summary>
        public static string salaDescripcionGarlo {
            get {
                return ResourceManager.GetString("salaDescripcionGarlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Ores.
        /// </summary>
        public static string salaDescripcionOres {
            get {
                return ResourceManager.GetString("salaDescripcionOres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Ramfez.
        /// </summary>
        public static string salaDescripcionRamfez {
            get {
                return ResourceManager.GetString("salaDescripcionRamfez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a salaExpulsarJugador.
        /// </summary>
        public static string salaExpulsarJugador {
            get {
                return ResourceManager.GetString("salaExpulsarJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string salaInstruccion {
            get {
                return ResourceManager.GetString("salaInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar una familia.
        /// </summary>
        public static string salaSeleccionarFamilia {
            get {
                return ResourceManager.GetString("salaSeleccionarFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De clic en el botón de “más” para para aceptar la solcitud.
        /// </summary>
        public static string solicitudAmistadInstruccion {
            get {
                return ResourceManager.GetString("solicitudAmistadInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar partida.
        /// </summary>
        public static string TituloBuscarPartida {
            get {
                return ResourceManager.GetString("TituloBuscarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string TituloCrearPartida {
            get {
                return ResourceManager.GetString("TituloCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin partida.
        /// </summary>
        public static string TituloFinPartida {
            get {
                return ResourceManager.GetString("TituloFinPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de partidas.
        /// </summary>
        public static string TituloHistorialDePartidas {
            get {
                return ResourceManager.GetString("TituloHistorialDePartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string TituloInicio {
            get {
                return ResourceManager.GetString("TituloInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio sesión.
        /// </summary>
        public static string TituloInicioSesion {
            get {
                return ResourceManager.GetString("TituloInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string TituloListaDeAmigos {
            get {
                return ResourceManager.GetString("TituloListaDeAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida.
        /// </summary>
        public static string TituloPartida {
            get {
                return ResourceManager.GetString("TituloPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil jugador.
        /// </summary>
        public static string TituloPerfilJugador {
            get {
                return ResourceManager.GetString("TituloPerfilJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personajes.
        /// </summary>
        public static string TituloPersonajes {
            get {
                return ResourceManager.GetString("TituloPersonajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro jugador.
        /// </summary>
        public static string TituloRegistroJugador {
            get {
                return ResourceManager.GetString("TituloRegistroJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string TituloSala {
            get {
                return ResourceManager.GetString("TituloSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione que desea hacer, vote para sacar a.
        /// </summary>
        public static string votacionInstruccion {
            get {
                return ResourceManager.GetString("votacionInstruccion", resourceCulture);
            }
        }
    }
}
